CREATE TABLE LABDATABASE.FUNCIONARIOS(
    NOME VARCHAR (50) NOT NULL,
    CPF VARCHAR (11) NOT NULL,
    SALARIO DECIMAL (10,2) NOT NULL,
    CODIGO_CARTAO INT NOT NULL
    CONSTRAINT FUNCIONARIOS_PK PRIMARY KEY (CODIGO_CARTAO)
 )

CREATE TABLE LABDATABASE.CARTAO_PONTO(
    DATA_ENTRADA DATE NOT NULL,
    DATA_SAIDA DATE NOT NULL,
    DIAS_TRABALHADOS VARCHAR(20) NOT NULL,
    CONSTRAINT CARTAO_PONTO_PK PRIMARY KEY (DATA_ENTRADA)
)


CREATE SEQUENCE LABDATABASE CARTAO_PONTO_CODIGO_CARTAO_PONTO_SEQ;

ALTER TABLE LABDATABASE.CARTAO_PONTO ADD CONSTRAINT FUNCIONARIOS_CARTAO_PONTO_FK FOREIGN KEY (CODIGO_CARTAO)

ALTER TABLE LABDATABASE.FUNCIONARIOS DROP CONSTRAINT CARTAO_PONTO_FK;

DROP SEQUENCE LABDATABASE.FUNCIONARIOS_CODIGO_FUNCIONARIOS_SEQ;
DROP SEQUENCE LABDATABASE.CARTAO_PONTO_CODIGO_CARTAO_PONTO_SEQ;

DROP TABLE LABDATABASE.FUNCIONARIOS;
DROP TABLE LABDATABASE.CARTAO_PONTO_FK;

GRANT ALL ON LABDATABASE.FUNCIONARIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.CARTAO_PONTO TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;